### ISSUE TITLE
Reaching out to @sandugadey

### ISSUE THREAD

**Issue by aseriy** [sandugadey/sonar-scm-clearcase#6]
@sandugadey, could you please let me know how to get in touch with you?
Thx

**Comment by aseriy** [comment]
The issue was resolved

**Comment by sandugadey** [comment]
@aseriy , Hi alex i was busy at office..can you please tell me ur issue..or send an email at sanudgadey@gmail.com

**Comment by aseriy** [comment]
I tried emailing you at the address above a couple of time today but it bounced back both times.
